import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { KpiCard } from "@/components/ui/KpiCard";
import { InfoPopover } from "@/components/ui/InfoPopover";
import { CustomChartTooltip } from "@/components/ui/ChartTooltip";
import { useDashboard } from "@/context/DashboardContext";
import { dashboardService } from "@/services/dashboardService";
import type { Rankings } from "@/lib/shared-types";
import { formatCurrency, formatNumber, formatKpiCurrency, formatKpiNumber } from "@/lib/utils";
import { Award, Package, Users } from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Cell,
} from "recharts";

export const Route = createFileRoute("/top-performers")({
  component: TopPerformersPage,
});

function TopPerformersPage() {
  const { dateRange, role, theme, openDrillDown } = useDashboard();
  const [data, setData] = useState<Rankings | null>(null);
  const [loading, setLoading] = useState(true);

  const isDark =
    theme === "dark" ||
    (theme === "system" &&
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);

  const axisColor = isDark ? "#F8FAFC" : "#0F172A";

  useEffect(() => {
    setLoading(true);
    dashboardService
      .getRankings(dateRange, role, 5)
      .then((res) => setData(res.data))
      .finally(() => setLoading(false));
  }, [dateRange, role]);

  const topProduct = data?.products[0];
  const topCustomer = data?.customers[0];

  const top5ProdSales = data?.products.reduce((s, p) => s + p.sales, 0) ?? 0;
  const top5CustSales = data?.customers.reduce((s, c) => s + c.sales, 0) ?? 0;

  const COLORS = isDark
    ? ["#38BDF8", "#818CF8", "#34D399", "#FBBF24", "#F472B6"]
    : ["#0F172A", "#2563EB", "#059669", "#D97706", "#6366F1"];

  return (
    <DashboardLayout
      title="Top Performers & Concentration"
    >
      {/* 4 KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4 shrink-0">
        <KpiCard
          title="Top Product"
          value={loading || !topProduct ? "—" : topProduct.name}
          comparison={topProduct ? `${formatKpiCurrency(topProduct.sales)} · ${formatKpiNumber(topProduct.units)} units` : "Selected period"}
          infoExplanation="Highest revenue-generating product during the selected period, excluding cancelled orders."
          infoFormula="Rank products by Sum(Quantity × Unit Price)"
          infoSource="OrderLine"
          onClick={() => {
            if (topProduct) openDrillDown("product", `Product Sales: ${topProduct.name}`, topProduct.id);
          }}
          icon={<Package className="w-4 h-4 text-blue-500" />}
        />
        <KpiCard
          title="Top Customer"
          value={loading || !topCustomer ? "—" : topCustomer.name}
          comparison={topCustomer ? `${formatKpiCurrency(topCustomer.sales)} · ${topCustomer.orders} orders` : "Selected period"}
          infoExplanation="Highest revenue-generating customer account during the selected period, excluding cancelled orders."
          infoFormula="Rank customers by Sum(Order Totals)"
          infoSource="CustomerOrder"
          onClick={() => {
            if (topCustomer) openDrillDown("customer", `Customer Orders: ${topCustomer.name}`, topCustomer.id);
          }}
          icon={<Users className="w-4 h-4 text-emerald-500" />}
        />
        <KpiCard
          title="Top 5 Products"
          value={loading ? "—" : formatKpiCurrency(top5ProdSales)}
          comparison="Combined revenue"
          infoExplanation="Total combined revenue generated by the top 5 ranking products in the selected range."
          infoFormula="Sum(Sales of Top 5 Products)"
          infoSource="Rankings metric"
          icon={<Award className="w-4 h-4 text-amber-500" />}
        />
        <KpiCard
          title="Top 5 Customers"
          value={loading ? "—" : formatKpiCurrency(top5CustSales)}
          comparison="Combined revenue"
          infoExplanation="Total combined revenue generated by the top 5 ranking client accounts in the selected range."
          infoFormula="Sum(Sales of Top 5 Customers)"
          infoSource="Rankings metric"
          icon={<Award className="w-4 h-4 text-purple-500" />}
        />
      </div>

      {/* 2 Primary Charts — fixed height on mobile, fill remaining on desktop */}
      <div className="flex-1 lg:min-h-0 grid grid-cols-1 lg:grid-cols-2 gap-4">

        {/* KEPT: Top 5 Products Ranking — most actionable product intelligence */}
        <div className="bento-card p-4 sm:p-5 flex flex-col h-80 lg:h-auto lg:min-h-0">
          <div className="flex items-center justify-between mb-3 shrink-0">
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center space-x-1.5">
                <Package className="w-4 h-4 text-blue-500" />
                <span>Top 5 Products by Sales Revenue</span>
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Leading catalog items ranked by gross sales</p>
            </div>
            <InfoPopover
              title="Top 5 Products by Sales"
              explanation="Ranking of top 5 catalog products generating the highest gross revenue in the selected period."
              formula="Rank products by Sum(OrderLine Quantity × Unit Price)"
              source="OrderLine + Product"
            />
          </div>
          <div className="flex-1 min-h-0 overflow-y-auto space-y-2 pr-1">
            {loading || !data ? (
              <div className="space-y-2">
                {[...Array(5)].map((_, i) => (
                  <div key={i} className="h-14 bg-slate-100 dark:bg-slate-800 rounded-xl animate-pulse" />
                ))}
              </div>
            ) : (
              data.products.map((item, idx) => (
                <div
                  key={item.id}
                  onClick={() => openDrillDown("product", `Product Sales: ${item.name}`, item.id)}
                  className="p-3 rounded-xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/30 hover:bg-slate-100/80 cursor-pointer transition-colors flex items-center justify-between"
                >
                  <div className="flex items-center space-x-3 min-w-0 pr-2">
                    <span className="w-7 h-7 rounded-full bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 text-xs font-bold flex items-center justify-center shrink-0">
                      {idx + 1}
                    </span>
                    <div className="min-w-0">
                      <div className="text-sm font-bold text-slate-900 dark:text-slate-100 truncate">
                        {item.name}
                      </div>
                      <div className="text-xs text-slate-400 mt-0.5">
                        {item.category} · {formatNumber(item.units)} units sold
                      </div>
                    </div>
                  </div>
                  <span className="text-sm font-bold text-slate-900 dark:text-slate-100 shrink-0">
                    {formatCurrency(item.sales)}
                  </span>
                </div>
              ))
            )}
          </div>
        </div>

        {/* KEPT: Top 5 Customers Ranking — critical account management intelligence */}
        <div className="bento-card p-4 sm:p-5 flex flex-col h-80 lg:h-auto lg:min-h-0">
          <div className="flex items-center justify-between mb-3 shrink-0">
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center space-x-1.5">
                <Users className="w-4 h-4 text-emerald-500" />
                <span>Top 5 Customers by Revenue</span>
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Key client accounts ranked by order total</p>
            </div>
            <InfoPopover
              title="Top 5 Customers by Revenue"
              explanation="Ranking of top 5 customer accounts generating the highest overall sales volume in the selected range."
              formula="Rank customers by Sum(CustomerOrder Totals)"
              source="CustomerOrder + Customer"
            />
          </div>
          <div className="flex-1 min-h-0 overflow-y-auto space-y-2 pr-1">
            {loading || !data ? (
              <div className="space-y-2">
                {[...Array(5)].map((_, i) => (
                  <div key={i} className="h-14 bg-slate-100 dark:bg-slate-800 rounded-xl animate-pulse" />
                ))}
              </div>
            ) : (
              data.customers.map((item, idx) => (
                <div
                  key={item.id}
                  onClick={() => openDrillDown("customer", `Customer Orders: ${item.name}`, item.id)}
                  className="p-3 rounded-xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/30 hover:bg-slate-100/80 cursor-pointer transition-colors flex items-center justify-between"
                >
                  <div className="flex items-center space-x-3 min-w-0 pr-2">
                    <span className="w-7 h-7 rounded-full bg-emerald-600 text-white text-xs font-bold flex items-center justify-center shrink-0">
                      {idx + 1}
                    </span>
                    <div className="min-w-0">
                      <div className="text-sm font-bold text-slate-900 dark:text-slate-100 truncate">
                        {item.name}
                      </div>
                      <div className="text-xs text-slate-400 mt-0.5">
                        {item.segment} · {item.orders} qualifying orders
                      </div>
                    </div>
                  </div>
                  <span className="text-sm font-bold text-emerald-600 dark:text-emerald-400 shrink-0">
                    {formatCurrency(item.sales)}
                  </span>
                </div>
              ))
            )}
          </div>
        </div>

        {/*
          COMMENTED OUT (less important — aggregate category/segment views):

          Sales Share by Product Category — bar chart of revenue per category; informative
          but the Top 5 Products list already surfaces which products (and thus categories) lead.
          <div className="lg:col-span-6 bento-card p-5">
            <h3>Sales Share by Product Category</h3>
            <BarChart data={data.byCategory} ...>
              <Bar dataKey="value" ...> <Cell fill={COLORS[...]} />
            </BarChart>
          </div>

          Sales Share by Customer Segment — bar chart of revenue per segment (Enterprise/SMB/Retail);
          secondary to the individual customer ranking above for account-level decision making.
          <div className="lg:col-span-6 bento-card p-5">
            <h3>Sales Share by Customer Segment</h3>
            <BarChart data={data.bySegment} fill={isDark ? "#818CF8" : "#6366F1"} ... />
          </div>
        */}
      </div>
    </DashboardLayout>
  );
}
