/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as TopPerformersRouteImport } from './routes/top-performers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const TopPerformersRoute = TopPerformersRouteImport.update({
  id: '/top-performers',
  path: '/top-performers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/receivables': typeof ReceivablesRoute
  '/top-performers': typeof TopPerformersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/receivables': typeof ReceivablesRoute
  '/top-performers': typeof TopPerformersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/operations': typeof OperationsRoute
  '/orders': typeof OrdersRoute
  '/receivables': typeof ReceivablesRoute
  '/top-performers': typeof TopPerformersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/receivables'
    | '/top-performers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/receivables'
    | '/top-performers'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/receivables'
    | '/top-performers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  InventoryRoute: typeof InventoryRoute
  OperationsRoute: typeof OperationsRoute
  OrdersRoute: typeof OrdersRoute
  ReceivablesRoute: typeof ReceivablesRoute
  TopPerformersRoute: typeof TopPerformersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-performers': {
      id: '/top-performers'
      path: '/top-performers'
      fullPath: '/top-performers'
      preLoaderRoute: typeof TopPerformersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  InventoryRoute: InventoryRoute,
  OperationsRoute: OperationsRoute,
  OrdersRoute: OrdersRoute,
  ReceivablesRoute: ReceivablesRoute,
  TopPerformersRoute: TopPerformersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
